rtx.skyBrightness = 2.0
rtx.bloom.burnIntensity = 2.0
rtx.pstrMaxBounces = 10

rtx.playerModel.backwardOffset = 25

rtx.volumetrics.enable = True
#rtx.volumetrics.froxelGridResolutionScale = 16
#rtx.volumetrics.froxelDepthSlices = 48
rtx.volumetrics.maxAccumulationFrames = 48
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2
rtx.volumetrics.froxelMaxDistanceMeters = 30

rtx.volumetrics.transmittanceColor = 0.930, 0.930, 0.930
rtx.volumetrics.transmittanceMeasurementDistanceMeters = 30
rtx.volumetrics.singleScatteringAlbedo = 0.830, 0.950, 0.950
rtx.volumetrics.anisotropy = 0.31
rtx.volumetrics.depthOffset = 0.18

rtx.volumetrics.enableFogRemap = False
rtx.volumetrics.fogRemapMaxDistanceMinMeters = 1
rtx.volumetrics.fogRemapMaxDistanceMaxMeters = 40
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMinMeters = 20
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMaxMeters = 100
rtx.volumetrics.fogRemapColorMultiscatteringScale = 0.1

rtx.volumetrics.enableAtmosphere = False
rtx.volumetrics.atmosphereInverted = False
rtx.volumetrics.atmosphereHeightMeters = 30

rtx.volumetrics.enableHeterogeneousFog = True
rtx.volumetrics.noiseFieldSubStepSizeMeters = 10
rtx.volumetrics.noiseFieldSpatialFrequency = 0.02
rtx.volumetrics.noiseFieldOctaves = 4
rtx.volumetrics.noiseFieldDensityScale = 0.0

rtx.dust.enable = True
rtx.dust.opacity = 0.0